# Generated by Django 5.1.2 on 2025-11-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='formatted_description_text',
            field=models.TextField(blank=True, help_text='Используйте теги <i>, <u>, <link>, <color>, <p>, <image> для форматирования'),
        ),
    ]
