# Generated by Django 5.1.2 on 2025-11-04 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_shop', '0002_product_formatted_description_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название скидки')),
                ('discount_type', models.CharField(choices=[('product', 'На товар'), ('category', 'На категорию'), ('all', 'На все товары')], max_length=20, verbose_name='Тип скидки')),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент скидки')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Фиксированная сумма скидки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sport_shop.category', verbose_name='Категория')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sport_shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'ordering': ['-created_at'],
            },
        ),
    ]
